spring:
  application:
    name: currency-exchange-service
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    show-sql: true
  h2:
    console:
      enabled=true
  datasource:
    url: "jdbc:h2:mem:coursemanagment"

  #
  #spring.jpa.hibernate.ddl-auto=update
  #spring.jpa.properties.hibernate.jdbc.time_zone=GMT+3
  #spring.datasource.url=jdbc:mysql://localhost:3310/ex
  #spring.datasource.username=ex
  #spring.datasource.password=nFLhPPKOnkW1FA1e

